# Generated by Django 2.2.13 on 2020-07-06 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gatherings',
        ),
    ]
