# Generated by Django 2.2.11 on 2020-03-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('processing', 'In process'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='new', max_length=16),
        ),
    ]
