# Generated by Django 2.2.13 on 2020-07-15 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200715_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='projects.Project'),
        ),
    ]
