# Generated by Django 2.2.13 on 2020-07-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200320_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('processing', 'In process'), ('denied', 'Denied'), ('negotiation', 'Negotiation'), ('opened', 'Opened'), ('closed', 'Closed')], default='processing', max_length=16),
        ),
    ]
