# Generated by Django 2.2.13 on 2020-06-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200320_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=6)),
                ('subscription_days', models.IntegerField(choices=[(None, 'Null'), (1, 'everyday'), (30, 'everymonth')])),
                ('payment_type', models.CharField(choices=[('s', 'sadaka'), ('z', 'zakat'), ('d', 'direct')], max_length=10)),
            ],
        ),
    ]
