# Generated by Django 2.2.13 on 2020-07-01 07:55

import accounts.models
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200701_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='denying_reason',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='documents',
            field=djongo.models.fields.ArrayField(default=[], model_container=accounts.models.Document),
        ),
        migrations.AddField(
            model_name='request',
            name='needy_category',
            field=models.CharField(blank=True, choices=[('large_families', 'Large Families'), ('low_income_families', 'Low Income Families'), ('retired_person', 'Retired Person'), ('single_parent_families', 'Single Parent Families'), ('orphan', 'Orphan'), ('refuge', 'Refuge'), ('person_without_a_fixed_residence_or_traveler_for_russians', 'Person without a fixed residence or traveler for russians'), ('person_without_a_fixed_residence_or_traveler_for_foreign', 'Person without a fixed residence or traveler for foreign'), ('debtor', 'debtor'), ('people_who_have_devoted_themselves_to_islam_or_for_study_of_the_Quran', 'People who have devoted themselves to islam or for study of the Quran'), ('children_or_adults_with_disabilities_or_people_with_severe_diseases', 'Children or adults with disabilities or people with severe diseases')], max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='accounts.User'),
        ),
    ]
