# Generated by Django 2.2.13 on 2020-06-30 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200624_1912'),
        ('projects', '0004_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_payment_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rrn', models.CharField(max_length=20, unique=True)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_payment_infos', to='accounts.User')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_payment_infos', to='projects.Payment')),
            ],
        ),
    ]
