# Generated by Django 2.2.13 on 2020-06-30 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200624_1912'),
        ('projects', '0005_card_payment_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card_payment_info',
            new_name='CardPaymentInfo',
        ),
    ]
