# Generated by Django 2.2.13 on 2020-07-01 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_paymentoptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentoptions',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payment_options', to='projects.Campaign'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='goal',
            field=models.IntegerField(default=0),
        ),
    ]
