# Generated by Django 2.2.13 on 2020-06-30 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200624_1912'),
        ('projects', '0007_otherpaymentinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherpaymentinfo',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_payment_infos', to='projects.Payment'),
        ),
        migrations.CreateModel(
            name='CashPaymentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_name', models.CharField(max_length=30)),
                ('payer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_payment_infos', to='accounts.User')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_payment_infos', to='projects.Payment')),
            ],
        ),
    ]
