# Generated by Django 2.2.13 on 2020-07-01 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200701_1625'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentOptions',
        ),
    ]
