# Generated by Django 2.2.13 on 2020-07-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_delete_paymentoptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='closing_reason',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
