# Generated by Django 2.2.13 on 2020-07-04 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_paymentoptions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentOptions',
        ),
    ]
