# Generated by Django 2.2.13 on 2020-07-01 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20200701_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardpaymentinfo',
            name='payer',
        ),
        migrations.RemoveField(
            model_name='cardpaymentinfo',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='cashpaymentinfo',
            name='payer',
        ),
        migrations.RemoveField(
            model_name='cashpaymentinfo',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='CampaignTransaction',
        ),
        migrations.DeleteModel(
            name='CardPaymentInfo',
        ),
        migrations.DeleteModel(
            name='CashPaymentInfo',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
