# Generated by Django 2.2.11 on 2020-03-14 12:17

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_auto_20200314_1334'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('images', djongo.models.fields.ArrayField(model_container=models.ImageField(upload_to=''))),
                ('tags', djongo.models.fields.ArrayField(model_container=models.CharField(max_length=16))),
                ('created_by', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Employee')),
                ('project', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project')),
            ],
        ),
    ]
