# Generated by Django 2.2.13 on 2020-06-22 21:14

from django.db import migrations, models
import djongo.models.fields
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='images',
            field=djongo.models.fields.ArrayField(model_container=news.models.ImageModel),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=djongo.models.fields.ArrayField(model_container=news.models.TagModel),
        ),
    ]
