"""
Django settings for zakat project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

from dotenv import load_dotenv
load_dotenv()

import os

# import django_heroku

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'dwhkv)h1i)yx@p2t4a=vhh33jv1*vi7577exxwdv(tf*(1yzw9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

FORM_RENDERER = 'django.forms.renderers.DjangoTemplates'

ALLOWED_HOSTS = []
# heroku
# ALLOWED_HOSTS = ['zakatkazan.herokuapp.com']


# Application definition

INSTALLED_APPS = [
    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    # 3rd-party
    'django_countries',
    'graphene_django',
    # our apps
    'accounts',
    'projects',
    'news',
    'payment',
    'partners',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'zakat.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'zakat.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

# For mongo
# DATABASES = {
#     'default': {
#         'ENGINE': 'djongo',
#         'NAME': 'zakat',
#         'CLIENT': {
#             'host': os.getenv('DB_HOST', 'localhost'),
#             # 'host': os.getenv('DB_HOST', ''),
#             'port': int(os.getenv('DB_PORT', 27017)),
#             'username': os.getenv('DB_USERNAME', ''),
#             'password': os.getenv('DB_PASSWORD', ''),
#             'authSource': 'admin',
#         }
#     }
# }

# For SQLite
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': os.getenv('DB_NAME', 'zakat'),
#         'USER': os.getenv('DB_USER', '') ,
#         'PASSWORD': os.getenv('DB_PASSWORD', ''),
#         'HOST': os.getenv('DB_HOST', '127.0.0.1'),
#         'PORT': os.getenv('DB_PORT', '5432'),
#     }
# }

GRAPHENE = {
    'SCHEMA': 'zakat.schema.schema'
}

# Register conversion rules from Djongo-specific fields
# from graphene_django.converter import convert_django_field
# from djongo.models import EmbeddedField, ArrayField


# @convert_django_field.register(EmbeddedField)
# def convert_embedded_field(field, registry=None):
#     return field


# @convert_django_field.register(ArrayField)
# def convert_embedded_field(field, registry=None):
#     return field


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AAUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

###
### Social Auth Part:
###

AUTHENTICATION_BACKENDS = (
    'social_core.backends.vk.VKOAuth2',  # vk authorization backend
    'social_core.backends.google.GoogleOAuth2',  # google authorization backend
    'social_core.backends.instagram.InstagramOAuth2',  # instagram authorization backend
    'django.contrib.auth.backends.ModelBackend',  # class authorization backend
)

# API APPs KEYS:(We need to change this keys when we'll deploy site!)
SOCIAL_AUTH_VK_OAUTH2_KEY = '7547650'
SOCIAL_AUTH_VK_OAUTH2_SECRET = 'jWnShHah7b0hX2GYucNj'

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '145625990573-nnu45c93abgsvljcn45o1oh8pc526f4h.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'kZaBBC_U_CCL3P9iqRjRDyyU'

SOCIAL_AUTH_INSTAGRAM_KEY = '3161780327269524'
SOCIAL_AUTH_INSTAGRAM_SECRET = '54d70a16b051d4106b3396eb1283570c'

# SOCIAL_AUTH_VK_OAUTH2_KEY = os.getenv('SOCIAL_AUTH_VK_OAUTH2_KEY','')
# SOCIAL_AUTH_VK_OAUTH2_SECRET = os.getenv('SOCIAL_AUTH_VK_OAUTH2_SECRET','')
# SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.getenv('SOCIAL_AUTH_GOOGLE_OAUTH2_KEY')
# SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.getenv('SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET')
# SOCIAL_AUTH_INSTAGRAM_KEY = os.getenv('SOCIAL_AUTH_INSTAGRAM_KEY')
# SOCIAL_AUTH_INSTAGRAM_SECRET = os.getenv('SOCIAL_AUTH_INSTAGRAM_SECRET')


SOCIAL_AUTH_URL_NAMESPACE = 'auth:social'

LOGIN_URL = '/auth/login/vk-oauth2/'

LOGIN_REDIRECT_URL = '/auth/test'  # change on right url
LOGOUT_REDIRECT_URL = '/'  # change on right url

###
###
###


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LANGUAGES = [
    ('en', 'English'),
    ('ru', 'Russian'),
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static')
# ]
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

CELERY_BROKER_URL = os.getenv('BROKER_URL', '')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_PASSWORD', '')
