# Generated by Django 2.2.13 on 2020-07-14 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=20, null=True)),
                ('subscription_days', models.IntegerField(choices=[('0', 'null'), ('1', 'everyday'), ('30', 'everymonth')], default='0')),
                ('type', models.CharField(choices=[('card', 'Card'), ('cash', 'Cash'), ('transfer', 'Transfer'), ('withdraw', 'Withdraw')], max_length=16)),
                ('description', models.TextField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='projects.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('payment_type', models.BooleanField(blank=True, help_text='Yes means payment was made through credit card, No - with cash money, Unknown - by other way', null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_options', to='projects.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='CashPaymentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_name', models.CharField(max_length=30)),
                ('payer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_payment_infos', to=settings.AUTH_USER_MODEL)),
                ('payment_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_payment_infos', to='payment.PaymentOptions')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_payment_infos', to='payment.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='CardPaymentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rrn', models.CharField(max_length=20, unique=True)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_payment_infos', to=settings.AUTH_USER_MODEL)),
                ('payment_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_payment_infos', to='payment.PaymentOptions')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_payment_infos', to='payment.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progressing', 'in_processing'), ('distribution', 'in_the_process_of_distribution'), ('mny_in_th_gthr', 'money_in_the_gathering'), ('in_th_process_of_trnsf_mny', 'in_the_process_of_transferring_money'), ('mny_trnsf', 'money_transferred')], max_length=40)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camping_transaction', to='projects.Campaign')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camping_transaction', to='payment.Transaction')),
            ],
        ),
    ]
