# Generated by Django 2.2.13 on 2020-07-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20200715_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('RUB', 'Russian Ruble'), ('USD', 'US. Dollar')], default='RUB', max_length=3),
        ),
    ]
