# Generated by Django 2.2.13 on 2020-07-01 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0011_auto_20200701_1005'),
        ('payment', '0002_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=20)),
                ('subscription_days', models.IntegerField(choices=[(None, 'Null'), (1, 'everyday'), (30, 'everymonth')])),
                ('type', models.CharField(choices=[('card', 'Card'), ('cash', 'Cash'), ('transfer', 'Transfer'), ('withdraw', 'Withdraw')], max_length=16)),
                ('description', models.TextField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='projects.Campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CashPaymentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_name', models.CharField(max_length=30)),
                ('payer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_payment_infos', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_payment_infos', to='payment.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='CardPaymentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rrn', models.CharField(max_length=20, unique=True)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_payment_infos', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_payment_infos', to='payment.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progressing', 'in_processing'), ('distribution', 'in_the_process_of_distribution'), ('mny_in_th_gthr', 'money_in_the_gathering'), ('in_th_process_of_trnsf_mny', 'in_the_process_of_transferring_money'), ('mny_trnsf', 'money_transferred')], max_length=40)),
                ('gathering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camping_transaction', to='projects.Campaign')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camping_transaction', to='payment.Transaction')),
            ],
        ),
    ]
