# Generated by Django 2.2.13 on 2020-07-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20200708_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('0', 'sadaka'), ('1', 'zakat'), ('2', 'direct')], default=0, max_length=4),
        ),
    ]
