# Generated by Django 2.2.13 on 2020-07-09 12:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0010_delete_paymentoptions'),
        ('payment', '0003_auto_20200708_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='subscription_days',
            field=models.IntegerField(choices=[('0', 'null'), ('1', 'everyday'), ('30', 'everymonth')], default='0'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('0', 'sadaka'), ('1', 'zakat'), ('2', 'direct')], default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='projects.Campaign'),
        ),
        migrations.CreateModel(
            name='CashPaymentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_name', models.CharField(max_length=30)),
                ('payer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_payment_infos', to=settings.AUTH_USER_MODEL)),
                ('payment_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_payment_infos', to='payment.PaymentOptions')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_payment_infos', to='payment.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='CardPaymentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rrn', models.CharField(max_length=20, unique=True)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_payment_infos', to=settings.AUTH_USER_MODEL)),
                ('payment_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_payment_infos', to='payment.PaymentOptions')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_payment_infos', to='payment.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progressing', 'in_processing'), ('distribution', 'in_the_process_of_distribution'), ('mny_in_th_gthr', 'money_in_the_gathering'), ('in_th_process_of_trnsf_mny', 'in_the_process_of_transferring_money'), ('mny_trnsf', 'money_transferred')], max_length=40)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camping_transaction', to='projects.Campaign')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camping_transaction', to='payment.Transaction')),
            ],
        ),
    ]
