# Generated by Django 2.2.13 on 2020-07-01 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_campaigntransaction_cardpaymentinfo_cashpaymentinfo_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
    ]
