# Generated by Django 2.2.13 on 2020-07-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20200709_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='subscription_days',
            field=models.IntegerField(choices=[(0, 'null'), (1, 'everyday'), (30, 'everymonth')], default=0),
        ),
    ]
