# Generated by Django 2.2.13 on 2020-07-14 15:29

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=16)),
                ('citizenship', django_countries.fields.CountryField(max_length=2)),
                ('religion', models.CharField(choices=[('muslim', 'Muslim'), ('christian', 'Christian'), ('jew', 'Jewish'), ('atheist', 'Atheist'), ('other', 'Others')], max_length=10)),
                ('birthdate', models.DateField()),
                ('education', models.CharField(max_length=128)),
                ('work', djongo.models.fields.EmbeddedField(model_container=accounts.models.Work, null=True)),
                ('marital_status', models.CharField(choices=[('married', 'Married'), ('divorced', 'Divorced'), ('single', 'Single'), ('widowed', 'Widowed'), ('other', 'Other')], max_length=10)),
                ('address', models.CharField(max_length=128)),
                ('cash_flow', djongo.models.fields.ArrayField(default=[], model_container=accounts.models.CashFlow)),
                ('related_documents', djongo.models.fields.ArrayField(default=[], model_container=accounts.models.Document)),
                ('contact_person', djongo.models.fields.EmbeddedField(model_container=accounts.models.FamilyMember, null=True)),
                ('family_members', djongo.models.fields.ArrayField(default=[], model_container=accounts.models.FamilyMember)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=16)),
                ('photo', models.ImageField(default='uploads/anon.png', upload_to='uploads')),
                ('bio', models.TextField()),
                ('position', models.CharField(max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
