# Generated by Django 3.0.3 on 2020-02-29 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=128)),
                ('position', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=16)),
                ('citizenship', django_countries.fields.CountryField(max_length=2)),
                ('religion', models.CharField(choices=[('muslim', 'Muslim'), ('christian', 'Christian'), ('jew', 'Jewish'), ('atheist', 'Atheist'), ('other', 'Others')], max_length=10)),
                ('birthdate', models.DateField()),
                ('education', models.CharField(max_length=128)),
                ('marital_status', models.CharField(choices=[('married', 'Married'), ('divorced', 'Divorced'), ('single', 'Single'), ('widowed', 'Widowed'), ('other', 'Other')], max_length=10)),
                ('address', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Work')),
            ],
        ),
    ]
