# Generated by Django 2.2.13 on 2020-07-15 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cash_flow',
        ),
    ]
