# Generated by Django 2.2.11 on 2020-03-06 19:58

import accounts.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cash_flow',
            field=djongo.models.fields.ArrayField(default=[], model_container=accounts.models.CashFlow),
        ),
    ]
