# Generated by Django 2.2.11 on 2020-03-06 20:30

import accounts.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_cash_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='related_documents',
            field=djongo.models.fields.ArrayField(default=[], model_container=accounts.models.Document),
        ),
    ]
