# Generated by Django 2.2.13 on 2020-07-15 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_cash_flow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='work',
        ),
    ]
