# Generated by Django 2.2.13 on 2020-07-15 08:33

import accounts.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='work',
            field=djongo.models.fields.EmbeddedField(blank=True, model_container=accounts.models.Work, null=True),
        ),
    ]
