# Generated by Django 2.2.11 on 2020-03-14 09:15

import accounts.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_related_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_person',
            field=djongo.models.fields.EmbeddedField(model_container=accounts.models.FamilyMember, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='family_members',
            field=djongo.models.fields.ArrayField(default=[], model_container=accounts.models.FamilyMember),
        ),
    ]
