# Generated by Django 2.2.13 on 2020-07-15 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='user',
            name='family_members',
        ),
        migrations.RemoveField(
            model_name='user',
            name='related_documents',
        ),
    ]
