# Generated by Django 2.2.13 on 2020-07-15 08:49

import accounts.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200715_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='related_documents',
            field=djongo.models.fields.ArrayField(blank=True, default=[], model_container=accounts.models.Document),
        ),
    ]
