# Generated by Django 2.2.13 on 2020-07-15 08:54

import accounts.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_related_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cash_flow',
            field=djongo.models.fields.ArrayField(blank=True, default=[], model_container=accounts.models.CashFlow),
        ),
    ]
