# Generated by Django 2.2.13 on 2020-06-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200314_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, default='uploads/anon.png', upload_to='uploads'),
        ),
    ]
