# Generated by Django 2.2.13 on 2020-07-06 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200624_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='related_documents',
        ),
    ]
