# Generated by Django 2.2.13 on 2020-07-06 09:55

import accounts.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_user_related_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pass_main', 'Passport main page'), ('pass_registration', 'Passport registration page'), ('birth', 'Birth certificate'), ('death', 'Death certificate'), ('marriage', 'Marriage certificate'), ('divorce', 'Divorce'), ('income', 'Income certificate'), ('unemployment', 'Unemployment office certificate'), ('medical', 'Disability/diagnosis'), ('study', 'Place of study'), ('loan', 'Loan'), ('rent', 'House book extract'), ('invoice', 'Invoice')], max_length=10)),
                ('title', models.CharField(max_length=128)),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('phone_number', models.CharField(max_length=16)),
                ('relation', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('son', 'Son'), ('daughter', 'Daughter'), ('brother', 'Brother'), ('sister', 'Sister'), ('other', 'Other')], max_length=16)),
                ('identification', djongo.models.fields.EmbeddedField(model_container=accounts.models.Document, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=128)),
                ('position', models.CharField(max_length=64)),
            ],
        ),
    ]
