# Generated by Django 2.2.13 on 2020-07-06 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_document_familymember_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cash_flow',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='user',
            name='family_members',
        ),
    ]
