# Generated by Django 2.2.13 on 2020-07-09 12:26

import accounts.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200707_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cash_flow',
            field=djongo.models.fields.ArrayField(default=[], model_container=accounts.models.CashFlow),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_person',
            field=djongo.models.fields.EmbeddedField(model_container=accounts.models.FamilyMember, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='family_members',
            field=djongo.models.fields.ArrayField(default=[], model_container=accounts.models.FamilyMember),
        ),
        migrations.AddField(
            model_name='user',
            name='related_documents',
            field=djongo.models.fields.ArrayField(default=[], model_container=accounts.models.Document),
        ),
    ]
