# Generated by Django 2.2.13 on 2020-07-10 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200709_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cash_flow',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='user',
            name='family_members',
        ),
        migrations.RemoveField(
            model_name='user',
            name='related_documents',
        ),
    ]
